language: php
sudo: false
dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.4

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install:
  - composer update

script:
  - ./vendor/bin/phpunit -v

jobs:
  include:
    # Test against latest Laravel 8.0 stable
    - php: 7.4
      install:
        - composer require laravel/framework:8.0.*

    # Test dev versions
    - php: 7.4
      if: type = cron
      install:
        - composer update

    - stage: Code Quality
      php: 7.4
      script:
        - ./vendor/bin/phpcs
        - ./vendor/bin/psalm

    - stage: Coverage
      php: 7.4
      install:
        - composer update
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml
      after_script:
        - php ./vendor/bin/php-coveralls -v
